import { StyleSheet } from "react-native";
import { COLORS } from "../src/config";
export { COLORS };

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  scroll: { padding: 20, paddingBottom: 40 },
  pageTitle: {
    textAlign: "center",
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: 1,
    color: COLORS.text,
    marginTop: 8,
    marginBottom: 10,
  },
  sub: {
    textAlign: "center",
    color: COLORS.textMuted,
    fontSize: 14,
    marginBottom: 14,
  },
  card: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.neutral200,
    borderRadius: 14,
    padding: 16,
  },

  frame: {
    alignSelf: "center",
    width: "86%",
    aspectRatio: 1,
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: COLORS.primary,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    marginBottom: 18,
    overflow: "hidden",
  },
  frameText: { color: COLORS.textMuted, fontSize: 13 },

  preview: { width: "100%", height: "100%" },

  captureWrap: { alignItems: "center", marginTop: 8 },
  captureBtnRing: {
    width: 82,
    height: 82,
    borderRadius: 41,
    borderWidth: 3,
    borderColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.white,
    elevation: 1,
  },
  captureBtnInner: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: COLORS.neutral100,
    alignItems: "center",
    justifyContent: "center",
  },
  captureLabel: { marginTop: 12, color: COLORS.textMuted, fontSize: 14 },

  photoBox: {
    alignSelf: "center",
    width: "80%",
    aspectRatio: 1.2,
    borderWidth: 2,
    borderColor: COLORS.neutral200,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 12,
    backgroundColor: COLORS.neutral100,
  },
  photoText: { color: COLORS.textMuted, fontSize: 13 },
  twoCols: { flexDirection: "row", gap: 16, marginTop: 8 },
  col: { flex: 1 },
  label: { color: COLORS.primary, fontWeight: "700", marginBottom: 6 },
  bullet: { color: COLORS.text, marginBottom: 4 },
  divider: {
    height: 1,
    backgroundColor: COLORS.neutral200,
    marginVertical: 16,
    opacity: 0.8,
  },
  sectionTitle: {
    textAlign: "center",
    color: COLORS.primary,
    fontWeight: "700",
    marginBottom: 10,
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 12,
  },
  recipeCard: {
    width: "31%",
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    backgroundColor: COLORS.white,
  },
  recipeTitle: {
    textAlign: "center",
    fontSize: 12,
    color: COLORS.text,
    marginTop: 8,
    paddingHorizontal: 4,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.06)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },
  loadingText: { marginTop: 10, color: COLORS.primary, fontWeight: "600" },
  actionsRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 14,
    marginTop: 12,
  },
  smallLink: {
    color: COLORS.primary,
    textDecorationLine: "underline",
    fontSize: 13,
  },
});
